#!/usr/bin/env python3
"""Build `_generated/publications.yaml` from CV YAML, BibTeX, CSL, and local PDFs."""

from __future__ import annotations

import argparse
import hashlib
import html as html_lib
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

import bibtexparser
from bibtexparser.bparser import BibTexParser
import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CV = ROOT / "cv-data" / "cv.yaml"
DEFAULT_BIB = ROOT / "cv-data" / "publications.bib"
DEFAULT_CSL = ROOT / "citation-style.csl"
DEFAULT_OUTPUT = ROOT / "_generated" / "publications.yaml"
DEFAULT_HASH = ROOT / "_generated" / "publications.hash"
DEFAULT_PAPERS_DIR = ROOT / "files" / "papers"

SECTION_LABELS = {
    "peer": "Peer-reviewed Articles",
    "working": "Working Papers",
    "other": "Other Publications",
    "book_chapters": "Book Chapters",
    "datasets": "Datasets",
}

SECTION_CATEGORIES = {
    "peer": "peer-reviewed",
    "working": "working-paper",
    "other": "other-publication",
    "book_chapters": "book-chapter",
    "datasets": "dataset",
}

ALLOWED_CV_FIELDS = {
    "key",
    "title",
    "coauthors",
    "link",
    "notes",
    "status",
    "year",
    "order",
    "selected",
    "show_on_cv",
    "show_on_website",
    "pdf",
    "doi",
    "url",
    "code",
    "data",
    "slides",
    "website_slug",
    "website_blurb",
    "cv_note",
    "tags",
    "title_override",
    "venue_override",
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cv", type=Path, default=DEFAULT_CV)
    parser.add_argument("--bib", type=Path, default=DEFAULT_BIB)
    parser.add_argument("--csl", type=Path, default=DEFAULT_CSL)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--hash-file", type=Path, default=DEFAULT_HASH)
    parser.add_argument("--papers-dir", type=Path, default=DEFAULT_PAPERS_DIR)
    parser.add_argument("--pandoc", default="quarto pandoc", help="Pandoc command; default uses Quarto's bundled Pandoc.")
    parser.add_argument("--force", action="store_true", help="Rebuild even if inputs are unchanged.")
    args = parser.parse_args()

    for path in (args.cv, args.bib):
        if not path.exists():
            raise FileNotFoundError(path)
    csl_path = args.csl if args.csl.exists() else None

    input_hash = compute_input_hash(args.cv, args.bib, csl_path, args.papers_dir, Path(__file__))
    if not args.force and args.output.exists() and args.hash_file.exists():
        if args.hash_file.read_text(encoding="utf-8").strip() == input_hash:
            print(f"Publication listing unchanged: {relative(args.output)}")
            return 0

    cv_data = yaml.safe_load(args.cv.read_text(encoding="utf-8")) or {}
    bib_entries = read_bibtex(args.bib)
    items = build_items(cv_data.get("publications") or {}, bib_entries, args.papers_dir)
    add_pandoc_references(items, args.bib, csl_path, args.pandoc)
    validate_items(items)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    output_text = "# Generated by scripts/build_publications_listing.py; do not edit by hand.\n"
    output_text += yaml.safe_dump(items, sort_keys=False, allow_unicode=True, width=1000)
    write_if_changed(args.output, output_text)
    write_if_changed(args.hash_file, input_hash + "\n")

    print(f"Wrote {len(items)} publication items to {relative(args.output)}")
    return 0


def read_bibtex(path: Path) -> dict[str, dict[str, Any]]:
    parser = BibTexParser(common_strings=True)
    parser.ignore_nonstandard_types = False
    parser.homogenize_fields = False
    database = bibtexparser.loads(path.read_text(encoding="utf-8"), parser=parser)
    malformed_entries = [comment.strip() for comment in database.comments if comment.lstrip().startswith("@")]
    if malformed_entries:
        labels = []
        for entry_text in malformed_entries:
            match = re.match(r"@\w+\s*\{\s*([^,\s]+)", entry_text)
            labels.append(match.group(1) if match else entry_text.splitlines()[0])
        raise ValueError(f"Malformed BibTeX entr{'y' if len(labels) == 1 else 'ies'}: {', '.join(labels)}")

    entries: dict[str, dict[str, Any]] = {}
    for entry in database.entries:
        key = entry.get("ID")
        if not key:
            continue
        if key in entries:
            raise ValueError(f"Duplicate BibTeX key: {key}")
        entries[key] = {k.lower(): clean_bibtex(v) for k, v in entry.items() if k not in {"ID"}}
        entries[key]["key"] = key
        entries[key]["entry_type"] = entry.get("ENTRYTYPE")
        entries[key]["bibtex"] = entry_to_bibtex(entry)
    return entries


def build_items(
    publication_sections: dict[str, list[dict[str, Any]]],
    bib_entries: dict[str, dict[str, Any]],
    papers_dir: Path,
) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    seen_keys: set[str] = set()
    position = 0

    for section, records in publication_sections.items():
        if records is None:
            continue
        if not isinstance(records, list):
            raise ValueError(f"Publication section must be a list: {section}")

        for record in records:
            position += 1
            if not isinstance(record, dict):
                raise ValueError(f"Publication record must be a mapping in section `{section}`")
            validate_cv_record(record)

            key = record.get("key")
            if key:
                if key in seen_keys:
                    raise ValueError(f"Duplicate publication key in CV data: {key}")
                seen_keys.add(key)
                if key not in bib_entries:
                    raise ValueError(f"Publication key not found in BibTeX: {key}")
                item = bib_item(section, position, record, bib_entries[key], papers_dir)
            else:
                item = manual_item(section, position, record, papers_dir)

            if item.get("show_on_website") is not False:
                items.append(drop_none(item))

    return items


def validate_cv_record(record: dict[str, Any]) -> None:
    unknown = sorted(set(record) - ALLOWED_CV_FIELDS)
    if unknown:
        label = record.get("key") or record.get("title") or "<unknown>"
        raise ValueError(f"Unknown publication field(s) for {label}: {', '.join(unknown)}")
    for field in ("show_on_cv", "show_on_website", "selected"):
        if field in record and record[field] is not None and not isinstance(record[field], bool):
            raise ValueError(f"{field} must be boolean for {record.get('key') or record.get('title')}")
    for field in ("url", "doi", "code", "data", "slides", "pdf", "link"):
        if field in record and record[field] is not None and not isinstance(record[field], str):
            raise ValueError(f"{field} must be a string for {record.get('key') or record.get('title')}")


def bib_item(section: str, position: int, record: dict[str, Any], bib: dict[str, Any], papers_dir: Path) -> dict[str, Any]:
    key = str(record["key"])
    title = record.get("title_override") or bib.get("title")
    authors = format_authors(bib.get("author"))
    year = record.get("year") or extract_year(bib.get("date") or bib.get("year"))
    date = normalize_date(bib.get("date") or bib.get("year"), year)
    venue = record.get("venue_override") or venue_from_bib(bib)

    item = base_item(section, position, record)
    item.update(
        {
            "key": key,
            "title": title,
            "authors": authors,
            "year": year,
            "date": date,
            "venue": venue,
            "entry_type": bib.get("entry_type"),
            "bibtex": bib.get("bibtex"),
        }
    )

    for field in ("doi", "url"):
        item[field] = record.get(field) or bib.get(field)
    for field in ("abstract", "volume", "number", "pages", "publisher", "booktitle"):
        item[field] = bib.get(field)

    add_pdf_link(item, key, record, papers_dir)
    return item


def manual_item(section: str, position: int, record: dict[str, Any], papers_dir: Path) -> dict[str, Any]:
    title = record.get("title")
    authors = join_people(["Brian Libgober", *[str(name) for name in record.get("coauthors") or []]])
    item = base_item(section, position, record)
    item.update(
        {
            "key": slugify(title or f"{section}-{position}"),
            "title": title,
            "authors": authors,
            "year": record.get("year"),
            "date": normalize_date(None, record.get("year")),
            "url": record.get("link") or record.get("url"),
            "notes": record.get("notes"),
            "citation": manual_display_text(authors, record.get("year"), title, record.get("venue_override"), record.get("status")),
        }
    )
    add_pdf_link(item, str(item["key"]), record, papers_dir)
    return item


def base_item(section: str, position: int, record: dict[str, Any]) -> dict[str, Any]:
    tags = record.get("tags") or []
    if isinstance(tags, str):
        tags = [tags]
    categories = [SECTION_CATEGORIES.get(section, section.replace("_", "-")), *tags]
    return {
        "section": section,
        "section_label": SECTION_LABELS.get(section, titleize(section)),
        "order": int(record.get("order") or position),
        "status": record.get("status"),
        "selected": bool(record.get("selected", False)),
        "show_on_cv": record.get("show_on_cv"),
        "show_on_website": record.get("show_on_website"),
        "website_slug": record.get("website_slug"),
        "website_blurb": record.get("website_blurb"),
        "cv_note": record.get("cv_note"),
        "categories": categories,
        "code": record.get("code"),
        "data": record.get("data"),
        "slides": record.get("slides"),
    }


def add_pandoc_references(items: list[dict[str, Any]], bib_path: Path, csl_path: Path | None, pandoc_command: str) -> None:
    keys = [str(item["key"]) for item in items if item.get("entry_type")]
    if not keys:
        return

    refs = render_references(keys, bib_path, csl_path, pandoc_command)
    missing = sorted(set(keys) - set(refs))
    if missing:
        raise ValueError(f"Pandoc/citeproc did not render reference(s): {', '.join(missing)}")

    for item in items:
        key = item.get("key")
        if key in refs:
            item["citation_html"] = refs[key]
            item["citation"] = html_to_text(refs[key])


def render_references(keys: list[str], bib_path: Path, csl_path: Path | None, pandoc_command: str) -> dict[str, str]:
    metadata = {
        "bibliography": str(bib_path.resolve()),
        "nocite": [f"@{key}" for key in keys],
    }
    if csl_path:
        metadata["csl"] = str(csl_path.resolve())

    with tempfile.TemporaryDirectory(prefix="pubs-citeproc-") as tmp:
        input_path = Path(tmp) / "references.md"
        input_path.write_text("---\n" + yaml.safe_dump(metadata, sort_keys=False) + "---\n", encoding="utf-8")
        command = [*pandoc_command.split(), str(input_path), "--citeproc", "--to=html"]
        result = subprocess.run(command, cwd=ROOT, check=False, text=True, capture_output=True)

    if result.returncode != 0:
        raise RuntimeError(f"Pandoc/citeproc failed:\n{result.stderr.strip()}")
    return extract_csl_entries(result.stdout)


def extract_csl_entries(html: str) -> dict[str, str]:
    pattern = re.compile(r'<div\s+([^>]*\bid="ref-([^"]+)"[^>]*)>\s*(.*?)\s*</div>', re.DOTALL)
    entries: dict[str, str] = {}
    for attrs, key, body in pattern.findall(html):
        if 'csl-entry' not in attrs:
            continue
        entries[key] = re.sub(r"\s+", " ", body).strip()
    return entries


def html_to_text(html: str) -> str:
    text = re.sub(r"<[^>]+>", "", html)
    return html_lib.unescape(re.sub(r"\s+", " ", text).strip())


def add_pdf_link(item: dict[str, Any], key: str, record: dict[str, Any], papers_dir: Path) -> None:
    if record.get("pdf"):
        pdf = ROOT / record["pdf"]
        if not pdf.exists():
            raise ValueError(f"Manual PDF path does not exist for {key}: {record['pdf']}")
        item["pdf"] = record["pdf"]
        return

    conventional_pdf = papers_dir / f"{key}.pdf"
    if conventional_pdf.exists():
        item["pdf"] = str(relative(conventional_pdf))


def venue_from_bib(bib: dict[str, Any]) -> str | None:
    return bib.get("journaltitle") or bib.get("journal") or bib.get("booktitle") or bib.get("publisher")


def format_authors(author_field: str | None) -> str | None:
    if not author_field:
        return None
    authors = [format_one_author(author.strip()) for author in author_field.split(" and ") if author.strip()]
    return join_people(authors)


def format_one_author(author: str) -> str:
    if "," not in author:
        return author
    last, first = [part.strip() for part in author.split(",", 1)]
    return f"{first} {last}".strip()


def join_people(names: list[str]) -> str | None:
    names = [name for name in names if name]
    if not names:
        return None
    if len(names) == 1:
        return names[0]
    if len(names) == 2:
        return f"{names[0]} and {names[1]}"
    return ", ".join(names[:-1]) + f", and {names[-1]}"


def manual_display_text(authors: Any, year: Any, title: Any, venue: Any, status: Any) -> str:
    parts = []
    if authors:
        parts.append(str(authors))
    if year:
        parts.append(str(year))
    if title:
        title_text = str(title).strip()
        punctuation = "" if title_text.endswith((".", "?", "!")) else "."
        parts.append(f'"{title_text}{punctuation}"')
    if venue:
        parts.append(str(venue))
    if status:
        parts.append(f"({status})")
    return " ".join(parts)


def entry_to_bibtex(entry: dict[str, Any]) -> str:
    key = entry.get("ID")
    entry_type = entry.get("ENTRYTYPE") or "misc"
    allowed_fields = {
        "author",
        "booktitle",
        "date",
        "doi",
        "edition",
        "editor",
        "isbn",
        "issue",
        "journaltitle",
        "journal",
        "number",
        "pages",
        "publisher",
        "title",
        "url",
        "volume",
        "year",
    }
    lines = [f"@{entry_type}{{{key},"]
    fields = sorted(k for k in entry if k.lower() in allowed_fields)
    for index, field in enumerate(fields):
        suffix = "," if index < len(fields) - 1 else ""
        lines.append(f"  {field} = {{{clean_bibtex(entry[field])}}}{suffix}")
    lines.append("}")
    return "\n".join(lines)


def clean_bibtex(value: Any) -> Any:
    if not isinstance(value, str):
        return value
    replacements = {
        r"\&": "&",
        r"\%": "%",
        "{": "",
        "}": "",
        "–": "-",
    }
    for old, new in replacements.items():
        value = value.replace(old, new)
    value = re.sub(r"\s+", " ", value)
    return value.strip()


def extract_year(value: Any) -> int | None:
    match = re.search(r"\d{4}", str(value or ""))
    return int(match.group(0)) if match else None


def normalize_date(value: Any, year: Any) -> str | None:
    text = str(value or "").strip()
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", text):
        return text
    if re.fullmatch(r"\d{4}-\d{2}", text):
        return f"{text}-01"
    if re.fullmatch(r"\d{4}", text):
        return f"{text}-01-01"
    if year:
        return f"{year}-01-01"
    return None


def validate_items(items: list[dict[str, Any]]) -> None:
    for item in items:
        key = item.get("key", "<unknown>")
        if not item.get("title"):
            raise ValueError(f"Generated publication item has no title: {key}")
        if not item.get("section_label"):
            raise ValueError(f"Generated publication item has no section label: {key}")
        if not item.get("citation"):
            raise ValueError(f"Generated publication item has no citation text: {key}")
        if item.get("entry_type") and not item.get("citation_html"):
            raise ValueError(f"BibTeX-backed item has no Pandoc-rendered citation_html: {key}")
        for field in ("show_on_cv", "show_on_website", "selected"):
            if field in item and item[field] is not None and not isinstance(item[field], bool):
                raise ValueError(f"{field} must be boolean for {key}")


def compute_input_hash(cv_path: Path, bib_path: Path, csl_path: Path | None, papers_dir: Path, script_path: Path) -> str:
    digest = hashlib.sha256()
    for path in [cv_path, bib_path, csl_path, script_path]:
        if path is None:
            continue
        digest.update(str(relative(path)).encode())
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    if papers_dir.exists():
        for pdf in sorted(papers_dir.glob("*.pdf")):
            stat = pdf.stat()
            digest.update(f"{relative(pdf)}:{stat.st_size}:{stat.st_mtime_ns}".encode())
            digest.update(b"\0")
    return digest.hexdigest()


def drop_none(item: dict[str, Any]) -> dict[str, Any]:
    return {key: value for key, value in item.items() if value is not None}


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def titleize(value: str) -> str:
    return value.replace("_", " ").title()


def slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def relative(path: Path) -> Path:
    try:
        return path.resolve().relative_to(ROOT)
    except ValueError:
        return path


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
