#!/usr/bin/env python3
"""Build Quarto partials from generated publications and shared CV data."""

from __future__ import annotations

import html
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
CV_PATH = ROOT / "cv-data" / "cv.yaml"
PUBLICATIONS_PATH = ROOT / "_generated" / "publications.yaml"
OUTPUT_DIR = ROOT / "_generated"

SECTION_ORDER = ["working", "peer", "other", "book_chapters", "datasets"]
SECTION_LABELS = {
    "peer": "Peer-reviewed Articles",
    "working": "Working Papers",
    "other": "Other Publications",
    "book_chapters": "Book Chapters",
    "datasets": "Datasets",
}


def main() -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    cv_data = read_yaml(CV_PATH)
    publications = read_yaml(PUBLICATIONS_PATH)

    write_partial("current-appointments.qmd", render_current_appointments(cv_data))
    write_partial("featured-publications.qmd", render_featured_publications(publications))
    write_partial("publications.qmd", render_publications(publications))
    write_partial("cv-sections.qmd", render_cv_sections(cv_data))
    write_partial("teaching.qmd", render_teaching(cv_data))
    write_partial("advising.qmd", render_advising(cv_data))

    print("Wrote generated Quarto partials to _generated/")
    return 0


def read_yaml(path: Path) -> Any:
    if not path.exists():
        raise FileNotFoundError(path)
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def write_partial(name: str, content: str) -> None:
    path = OUTPUT_DIR / name
    text = "<!-- Generated by scripts/build_site_partials.py; do not edit by hand. -->\n\n"
    text += "```{=html}\n" + content.rstrip() + "\n```\n"
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return
    path.write_text(text, encoding="utf-8")


def render_current_appointments(cv_data: dict[str, Any]) -> str:
    current = [
        item for item in cv_data.get("appointments", [])
        if item.get("date_end") in (None, "", "present", "Present")
    ]
    if not current:
        current = cv_data.get("appointments", [])[:2]

    rows = ['<ul class="current-appointments">']
    for item in current:
        affiliations = item.get("affiliations") or []
        titles = []
        for affiliation in affiliations:
            title = affiliation.get("title")
            dept = affiliation.get("dept")
            qualifier = affiliation.get("qualifier")
            line = join_parts([title, qualifier, dept], ", ")
            if line:
                titles.append(line)
        title_text = "; ".join(titles)
        rows.append(
            "<li>"
            f"<strong>{esc(item.get('institution'))}</strong>"
            f"<span>{esc(title_text)}</span>"
            "</li>"
        )
    rows.append("</ul>")
    return "\n".join(rows)


def render_featured_publications(publications: list[dict[str, Any]]) -> str:
    selected = [item for item in publications if item.get("selected")]
    if not selected:
        selected = [
            item for item in publications
            if item.get("section") in {"peer", "working"}
        ][:5]

    rows = ['<div class="featured-publications">']
    for item in selected[:6]:
        rows.append(render_publication_entry(item, compact=True))
    rows.append("</div>")
    return "\n".join(rows)


def render_publications(publications: list[dict[str, Any]]) -> str:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in publications:
        grouped[item.get("section", "other")].append(item)

    sections = []
    for section in [*SECTION_ORDER, *sorted(set(grouped) - set(SECTION_ORDER))]:
        items = grouped.get(section)
        if not items:
            continue
        label = SECTION_LABELS.get(section) or items[0].get("section_label") or titleize(section)
        sections.append((section, label, sorted(items, key=lambda record: record.get("order", 9999))))

    if not sections:
        return ""

    parts = ['<div class="research-tabs">', '<ul class="nav nav-tabs" id="research-tabs" role="tablist">']
    for index, (section, label, items) in enumerate(sections):
        tab_id = f"tab-{safe_id(section)}"
        panel_id = f"panel-{safe_id(section)}"
        active = index == 0
        active_class = " active" if active else ""
        selected = "true" if active else "false"
        parts.append(
            f'<li class="nav-item" role="presentation">'
            f'<button class="nav-link{active_class}" id="{tab_id}" data-bs-toggle="tab" '
            f'data-bs-target="#{panel_id}" type="button" role="tab" '
            f'aria-controls="{panel_id}" aria-selected="{selected}">'
            f'{esc(label)}'
            f'</button></li>'
        )
    parts.append("</ul>")
    parts.append('<div class="tab-content research-tab-content" id="research-tab-content">')

    for index, (section, label, items) in enumerate(sections):
        tab_id = f"tab-{safe_id(section)}"
        panel_id = f"panel-{safe_id(section)}"
        pane_class = "tab-pane fade show active" if index == 0 else "tab-pane fade"
        parts.append(
            f'<section class="{pane_class}" id="{panel_id}" role="tabpanel" '
            f'aria-labelledby="{tab_id}" tabindex="0">'
        )
        parts.append(f'<h2 class="visually-hidden">{esc(label)}</h2>')
        parts.append('<div class="publication-list">')
        for item in sorted(items, key=lambda record: record.get("order", 9999)):
            parts.append(render_publication_entry(item))
        parts.append("</div>")
        parts.append("</section>")
    parts.append("</div>")
    parts.append("</div>")
    return "\n\n".join(parts)


def render_publication_entry(item: dict[str, Any], compact: bool = False) -> str:
    key = safe_id(item.get("key"))
    classes = "publication-entry publication-entry-compact" if compact else "publication-entry"
    year = item.get("year") or ""
    status = item.get("status")
    title = item.get("title") or "Untitled"
    authors = item.get("authors")
    citation = item.get("citation_html") or esc(item.get("citation"))
    bibtex = item.get("bibtex")
    notes = item.get("notes") or item.get("cv_note")
    links = publication_links(item)
    pdf_url = publication_pdf_url(item)
    title_html = esc(title)
    if pdf_url:
        title_html = f'<a href="{esc(pdf_url)}">{title_html}</a>'

    pieces = [
        f'<article class="{classes}" id="pub-{key}">',
        f'  <div class="pub-year">{esc(year)}</div>',
        '  <div class="pub-body">',
        '    <p class="pub-heading">',
        f'      <span class="pub-title">{title_html}</span>',
    ]
    if authors:
        pieces.append(f'      <span class="pub-authors">{esc(authors)}</span>')
    pieces.append("    </p>")
    if notes:
        pieces.append(f'    <p class="pub-note">{esc(notes)}</p>')
    if status or links or (not compact and (citation or bibtex)):
        pieces.append('    <div class="pub-meta-row">')
        if status:
            pieces.append(f'      <span class="pub-status">{esc(status)}</span>')
        if links:
            pieces.append(f'      <span class="pub-links">{links}</span>')
    if not compact and (citation or bibtex):
        if citation:
            pieces.append('      <details class="pub-detail">')
            pieces.append("        <summary>Suggested Citation</summary>")
            pieces.append(f'        <p class="pub-citation">{citation}</p>')
            pieces.append("      </details>")
        if bibtex:
            pieces.append('      <details class="pub-detail">')
            pieces.append("        <summary>BibTeX</summary>")
            pieces.append(f'        <pre class="pub-bibtex"><code>{esc(bibtex)}</code></pre>')
            pieces.append("      </details>")
    if status or links or (not compact and (citation or bibtex)):
        pieces.append("    </div>")
    pieces.extend(["  </div>", "</article>"])
    return "\n".join(pieces)


def publication_links(item: dict[str, Any]) -> str:
    links = []
    seen = set()
    has_doi = False
    doi = item.get("doi")
    if doi:
        url = str(doi)
        if not url.startswith(("http://", "https://")):
            url = f"https://doi.org/{url}"
        links.append(resource_link(url, "DOI"))
        seen.add(url)
        has_doi = True

    for field, label in [
        ("url", "Publisher Link"),
        ("pdf", "PDF"),
        ("code", "Code"),
        ("data", "Data"),
        ("slides", "Slides"),
    ]:
        url = item.get(field)
        if not url:
            continue
        if field == "url" and has_doi:
            continue
        url = str(url)
        if field == "pdf" and not url.startswith(("http://", "https://", "/")):
            url = f"/{url}"
        if url in seen:
            continue
        if field == "url" and is_doi_url(url):
            label = "DOI"
        links.append(resource_link(url, label))
        seen.add(url)
    return "\n".join(links)


def publication_pdf_url(item: dict[str, Any]) -> str | None:
    url = item.get("pdf")
    if not url:
        return None
    url = str(url)
    if not url.startswith(("http://", "https://", "/")):
        url = f"/{url}"
    return url


def is_doi_url(url: str) -> bool:
    normalized = url.lower().removeprefix("http://").removeprefix("https://")
    return normalized.startswith("doi.org/") or normalized.startswith("dx.doi.org/")


def render_cv_sections(cv_data: dict[str, Any]) -> str:
    parts = [
        "<h2>Appointments</h2>",
        render_appointments(cv_data.get("appointments", [])),
        "<h2>Education</h2>",
        render_education(cv_data.get("education", [])),
        "<h2>Grants and Fellowships</h2>",
        render_grants(cv_data.get("grants", [])),
        "<h2>Invited Talks</h2>",
        render_talks(cv_data.get("invited_talks", [])),
        "<h2>Service</h2>",
        render_service(cv_data.get("service", {})),
    ]
    return "\n\n".join(parts)


def render_appointments(appointments: list[dict[str, Any]]) -> str:
    rows = ['<div class="timeline-list">']
    for item in appointments:
        rows.append('<section class="timeline-item">')
        rows.append(f'  <div class="timeline-date">{esc(date_range(item))}</div>')
        rows.append('  <div>')
        rows.append(f'    <h3>{esc(item.get("institution"))}</h3>')
        for affiliation in item.get("affiliations") or []:
            title = join_parts(
                [affiliation.get("title"), affiliation.get("qualifier"), affiliation.get("dept")],
                ", ",
            )
            rows.append(f'    <p>{esc(title)}</p>')
        rows.append("  </div>")
        rows.append("</section>")
    rows.append("</div>")
    return "\n".join(rows)


def render_education(education: list[dict[str, Any]]) -> str:
    rows = ['<div class="compact-list">']
    for item in education:
        degree = join_parts([item.get("degree"), item.get("field")], " ")
        detail = join_parts([item.get("honors"), item.get("details")], "; ")
        rows.append('<section class="compact-item">')
        rows.append(f'  <h3>{esc(degree)}</h3>')
        rows.append(f'  <p>{esc(item.get("institution"))}, {esc(item.get("year"))}</p>')
        if detail:
            rows.append(f'  <p class="muted">{esc(detail)}</p>')
        rows.append("</section>")
    rows.append("</div>")
    return "\n".join(rows)


def render_grants(grants: list[dict[str, Any]]) -> str:
    rows = ['<div class="timeline-list">']
    for item in sorted(grants, key=lambda record: str(record.get("date_start", "")), reverse=True):
        title = item.get("name") or item.get("organization")
        detail = join_parts([item.get("organization"), item.get("amount")], " | ")
        rows.append('<section class="timeline-item">')
        rows.append(f'  <div class="timeline-date">{esc(date_range(item))}</div>')
        rows.append('  <div>')
        rows.append(f'    <h3>{esc(title)}</h3>')
        if detail:
            rows.append(f'    <p>{esc(detail)}</p>')
        rows.append("  </div>")
        rows.append("</section>")
    rows.append("</div>")
    return "\n".join(rows)


def render_talks(talks: list[dict[str, Any]]) -> str:
    rows = ['<div class="timeline-list talk-list">']
    for item in sorted(talks, key=lambda record: str(record.get("date", "")), reverse=True):
        rows.append('<section class="timeline-item">')
        rows.append(f'  <div class="timeline-date">{esc(item.get("date"))}</div>')
        rows.append('  <div>')
        rows.append(f'    <h3>{esc(item.get("title"))}</h3>')
        if item.get("host"):
            rows.append(f'    <p>{esc(item.get("host"))}</p>')
        rows.append("  </div>")
        rows.append("</section>")
    rows.append("</div>")
    return "\n".join(rows)


def render_service(service: dict[str, Any]) -> str:
    rows = ['<div class="compact-list">']
    for field, items in service.items():
        rows.append('<section class="compact-item">')
        rows.append(f'  <h3>{esc(titleize(field))}</h3>')
        rows.append("  <ul>")
        if field == "departmental":
            for institution in items or []:
                for item in institution.get("items") or []:
                    label = join_parts(
                        [date_range(item), item.get("role"), item.get("organization"), institution.get("institution")],
                        " | ",
                    )
                    rows.append(f"    <li>{esc(label)}</li>")
        else:
            for item in items or []:
                label = join_parts([date_range(item), item.get("role"), item.get("organization")], " | ")
                rows.append(f"    <li>{esc(label)}</li>")
        rows.append("  </ul>")
        rows.append("</section>")
    rows.append("</div>")
    return "\n".join(rows)


def render_teaching(cv_data: dict[str, Any]) -> str:
    rows = []
    for institution in cv_data.get("teaching", []):
        rows.append(f"<h2>{esc(institution.get('institution'))}</h2>")
        rows.append('<div class="course-grid">')
        for course in institution.get("courses") or []:
            term = join_parts([course.get("term"), course.get("year")], " ")
            rows.append('<section class="course-item">')
            rows.append(f'  <h3>{esc(course.get("title"))}</h3>')
            rows.append(f'  <p>{esc(term)}</p>')
            if course.get("level"):
                rows.append(f'  <span>{esc(course.get("level"))}</span>')
            rows.append("</section>")
        rows.append("</div>")
    return "\n\n".join(rows)


def render_advising(cv_data: dict[str, Any]) -> str:
    advising = cv_data.get("advising", {})
    rows = ["<h2>Advising</h2>", '<div class="compact-list">']
    graduate = advising.get("graduate", {})
    for label, key in [
        ("Current Graduate Committees", "current_committees"),
        ("Former Graduate Committees", "former_committees"),
    ]:
        items = graduate.get(key) or []
        if not items:
            continue
        rows.append('<section class="compact-item">')
        rows.append(f"  <h3>{label}</h3>")
        rows.append("  <ul>")
        for item in items:
            name = person_link(item)
            detail = join_parts([item.get("institution") or item.get("phd_institution"), item.get("year")], ", ")
            rows.append(f"    <li>{name}{': ' + esc(detail) if detail else ''}</li>")
        rows.append("  </ul>")
        rows.append("</section>")

    undergraduate = advising.get("undergraduate", {})
    for label, key in [
        ("Undergraduate Theses", "theses"),
        ("Research Assistants", "ras"),
        ("Course-Based Research", "courses"),
    ]:
        items = undergraduate.get(key) or []
        if not items:
            continue
        rows.append('<section class="compact-item">')
        rows.append(f"  <h3>{label}</h3>")
        rows.append("  <ul>")
        for item in items:
            detail = item.get("date") or date_range(item)
            rows.append(f"    <li>{person_link(item)}{': ' + esc(detail) if detail else ''}</li>")
        rows.append("  </ul>")
        rows.append("</section>")
    rows.append("</div>")
    return "\n".join(rows)


def person_link(item: dict[str, Any]) -> str:
    name = esc(item.get("name"))
    website = item.get("website")
    if website:
        return link(str(website), name)
    return name


def date_range(item: dict[str, Any]) -> str:
    if item.get("date_display"):
        return str(item.get("date_display"))
    start = item.get("date_start")
    end = item.get("date_end")
    if item.get("ongoing") and not end:
        end = "present"
    if start and (end is None or end == ""):
        end = "present"
    if start and end and str(start) != str(end):
        return f"{start}-{end}"
    return str(start or end or "")


def link(url: str, label: str) -> str:
    return f'<a href="{esc(url)}">{esc(label)}</a>'


def resource_link(url: str, label: str) -> str:
    icon = resource_icon(label)
    icon_html = f'<i class="{icon}" aria-hidden="true"></i>' if icon else ""
    return f'<a href="{esc(url)}" class="pub-resource pub-resource-{safe_id(label).lower()}">{icon_html}<span>{esc(label)}</span></a>'


def resource_icon(label: str) -> str:
    return {
        "DOI": "ai ai-doi",
        "PDF": "fa-solid fa-file-pdf",
        "Publisher Link": "fa-solid fa-arrow-up-right-from-square",
        "Code": "fa-solid fa-code",
        "Data": "fa-solid fa-table",
        "Slides": "fa-solid fa-display",
    }.get(label, "fa-solid fa-link")


def esc(value: Any) -> str:
    if value is None:
        return ""
    return html.escape(str(value), quote=True)


def safe_id(value: Any) -> str:
    return "".join(char if char.isalnum() or char in "-_" else "-" for char in str(value or "item"))


def join_parts(parts: list[Any], separator: str) -> str:
    return separator.join(str(part) for part in parts if part not in (None, ""))


def titleize(value: str) -> str:
    return value.replace("_", " ").title()


if __name__ == "__main__":
    raise SystemExit(main())
